### ISSUE TITLE
escapeStaticString removes character preceding single quote

### ISSUE THREAD

**Issue by turrea** [tinovyatkin/babel-plugin-html-tag#1]
https://github.com/tinovyatkin/babel-plugin-html-tag/blob/master/index.js#L21

The problem is `text.replace(/[^\\]'/g, "\\'")` removes preceding character because it is part of the match i.e. `my 'quoted' string` becomes `my\'quote\'string` instead of `my \'quoted\' string`.

I think we can change to use negative lookbehind instead `text.replace(/(?<!\\)'/g, "\\'")`.

**Comment by tinovyatkin** [comment]
Thank you for good catch! Do you mind to do a pull request?

**Comment by turrea** [comment]
Opened PR. Also tried to add a simple test example for angular.

**Comment by tinovyatkin** [comment]
Thank you! Merged and published as `1.0.6`
